### PR TITLE
added displayName, companyName and contactNumber to enabled users view

### PR DESCRIPTION
**Pull request by thedoktor**
The properties will only display if they are present on the model. In the absence of a displayName the title will be the username.

### CODE REVIEW

**Comment by mansona** [comment]
just nitpicking but can you make them go next to each other instead of on top of each other?

**Comment by thedoktor** [comment]
@mansona

**Comment by mansona** [comment]
Much nicer 💯

**Comment by mansona** [comment]
looks good, merging :+1:

**Pull request merged**
